### ISSUE TITLE
可以使用GitHub action或者腾讯云脚本来进行使用吗？

### ISSUE THREAD

**Issue by fatinghenji** [luminoleon/epicgames-claimer#1]
使用GitHub action或者腾讯云脚本可以不用开电脑自动定时运行。
会在以后的版本中支持吗？

**Comment by luminoleon** [comment]
我会考虑支持。感谢提出建议。

**Comment by luminoleon** [comment]
Github Actions我都已经做好了，结果在网上查到了不少Github账号被封禁的消息。
现在我可能要考虑删掉Actions这部分了……

另外这个程序运行需要Chromium和桌面环境，腾讯云脚本的支持可能比较困难，我不打算做。

**Comment by fatinghenji** [comment]
请问现行版本可以直接在centos里面用docker跑起来吗？还是说需要参照linux的方法？

**Comment by luminoleon** [comment]
只要是Linux内核的系统都可以直接用Docker运行，包括CentOS。

**Comment by fatinghenji** [comment]
我对于linux的命令行了解不多，现在很多操作都是跟着百度出来的结果直接复制粘贴的。
我如果想在我的腾讯云服务器上跑您写的脚本，是不是需要先使用curl命令下载压缩包，解压之后，然后再使用docker命令？
另外，我应该怎么配置登陆的邮箱和密码呢？

**Comment by luminoleon** [comment]
你可以先按照网上的教程安装Docker，然后执行这条命令：
`docker run -it -e TZ=Asia/Shanghai -v ~/epicgames-claimer/User_Data:/User_Data luminoleon/epicgames-claimer`

这条命令会从Docker Hub拉取luminoleon/epicgames-claimer镜像，并创建一个交互式的容器。等待一段时间后，会提示输入Email、Password、两步验证代码。完成登录后会显示“Login succesed.”和“Claim has started.”，这时可以输入Ctrl+P+Q退出交互式环境并且保持容器在后台运行。

输入`docker ps`可以查看后台正在运行的容器，`docker logs 容器ID或名称`可以查看日志，`docker stop 容器ID或名称` 可以停止容器，`docker rm 容器ID或名称`可以删除容器，`docker image rm 镜像名称`可以删除镜像。

如果要更新镜像，可以输入`docker pull luminoleon/epicgames-claimer`。

**Comment by fatinghenji** [comment]
非常感谢！

**Comment by fatinghenji** [comment]
![image](https://user-images.githubusercontent.com/37131177/119345390-64c5ce00-bccb-11eb-983e-22086d7fca1d.png)
我现在安装的是python3.8，是因为这个的原因报错吗？

**Comment by luminoleon** [comment]
和Python的版本没有关系，镜像里已经包含了一个Python。不好意思我现在对这个问题不是很有头绪，我可能需要一段时间来解决这个问题。

或许你可以试一下`docker run -it -e TZ=Asia/Shanghai -v ~/epicgames-claimer/User_Data:/User_Data luminoleon/epicgames-claimer:1.2.2`，我不能保证这个一定可以成功。

**Comment by fatinghenji** [comment]
命令行1：
![image](https://user-images.githubusercontent.com/37131177/119348090-fbe05500-bcce-11eb-903f-afbfd98dcdb3.png)
命令行2：
成功运行
