### ISSUE TITLE
腾讯云函数更新完之后默认语言变成英语

### ISSUE THREAD

**Issue by leicancun** [luminoleon/epicgames-claimer#101]
更新最新版1.6.13之后,通知的默认语言变成了英语,在环境变量里设置了lang=zh也不行,不清楚是哪里出了问题

**Comment by luminoleon** [comment]
不好意思……似乎我不该使用lang这个名称。它的值会被替换成系统语言。
我会给这个参数换个名称.

**Comment by leicancun** [comment]
> 不好意思……似乎我不该使用lang这个名称。它的值会被替换成系统语言。 我会给这个参数换个名称.

好的,感谢大佬😊

**Comment by luminoleon** [comment]
v1.6.14已解决，`--lang`修改为`--push-lang`。
