### ISSUE TITLE
hCAPTCHA

### ISSUE THREAD

**Issue by 2096779623** [luminoleon/epicgames-claimer#11]
![image](https://user-images.githubusercontent.com/57583560/130309277-e4e389ef-7c7b-4393-bd7c-14999a107cec.png)
怎么跳过或者识别验证码？

**Comment by luminoleon** [comment]
这个应该是因为某种原因触发了Epic的反Bot机制。等一天或者几个小时能会好。

我不确定验证码出现的原因。通常情况下应该是不会跳出验证的。
识别验证码有点困难，我大概弄不好。
