### ISSUE TITLE
[讨论]是否有可能把机器人校验转发出来？

### ISSUE THREAD

**Issue by HEXtoDEC** [luminoleon/epicgames-claimer#110]
如题，是否有可能，可以起一个WEB服务把机器人校验嵌套转发过来，使用浏览器打开这个转发页面进行生物交互。

**Comment by 13108271651** [comment]
都这样了，还不如手动领取快了

**Comment by HEXtoDEC** [comment]
> 都这样了，还不如手动领取快了

一般情况下，也就第一次会给机器人校验。
