### ISSUE TITLE
建议把基础镜像由 ubuntu 换成 alpine

### ISSUE THREAD

**Issue by yazawaniconii** [luminoleon/epicgames-claimer#13]
用 ubuntu 做基础镜像打包出来的镜像太大了，而 alpine 的镜像大小只有 5 MB 左右，用 alpine 的话镜像大小会小很多

**Comment by luminoleon** [comment]
现在有一个问题，基础镜像换成Alpine之后会触发人机验证。我不知道是哪里的问题，可能解决不了。

**Comment by luminoleon** [comment]
Alpine镜像已上传，大概400MB。

tag: latest-alpine, 1.6.7-alpine, alpine
