### ISSUE TITLE
关于docker配置

### ISSUE THREAD

**Issue by guitarzsr** [luminoleon/epicgames-claimer#13]
首先感谢作者带来了这么好的东东，想请教一下，在Docker部署时，是否支持添加变量、路径等形式来定义epic账户等配置信息？如支持应怎样操作？谢谢！

**Comment by guitarzsr** [comment]
感谢回复，我描述的可能不是很清楚，在您回复之前我已经通过命令行的方式完成了部署，提问是想通过unraid自带管理/Portainer ce等图形化界面进行部署

**Comment by luminoleon** [comment]
以前的版本可以通过command传递参数，不过现在的最新镜像可以通过环境变量来传递参数了。可以在图形界面里用“Env”设置界面来设定参数。

还是参照这个文档[README_DOCKER.md](https://github.com/luminoleon/epicgames-claimer/blob/master/docs/README_DOCKER.md)

**Comment by guitarzsr** [comment]
好嘞，我研究一下，谢谢

**Comment by guitarzsr** [comment]
您好，实测在UnRaid下，采用添加变量（Variable）的方式完成部署并测试通过。日志显示“All available weekly free games are already in your library.”（因为之前已经领过了）。另有一个不情之请，我能否撰写文章推广本项目？内文将带有项目作者及GitHub地址，谢谢

**Comment by luminoleon** [comment]
当然可以。^ ^
