### ISSUE TITLE
希望作者把参数提到环境变量中，以适配docker-compose

### ISSUE THREAD

**Issue by FormatToday** [luminoleon/epicgames-claimer#15]
我准备在compose中使用本镜像，但是用户名密码现在是以参数形式传递的，可否改成和时区一样使用环境变量， 这样即可使用compose了

**Comment by luminoleon** [comment]
我对docker-compose不是很了解，不知道是否可以用command来传递参数。

如果能行的话我就不用再改代码了。

**Comment by FormatToday** [comment]
好像不行，docker-compose一般都是用`environment`传参的，这个python可以用`os.environ.get('key_name')`获取到变量值，应该在代码中获取参数那块添加一下就行了。因为python技术不到位，自己不会改。。。。

**Comment by luminoleon** [comment]
新的Docker镜像我已经上传了。如果运行有问题请告诉我。

**Comment by FormatToday** [comment]
万分感谢，我稍后试一下

**Comment by FormatToday** [comment]
#18 添加了compose的使用说明
