### ISSUE TITLE
今天部署麻花藤云函数,提示有错误

### ISSUE THREAD

**Issue by iso-lib** [luminoleon/epicgames-claimer#15]
{
	"resource": "/usr/local/var/functions/ap-hongkong/lam-pz3lkhre/helloworld-1633773615/src/epicgames_claimer.py",
	"owner": "python",
	"code": "no-member",
	"severity": 8,
	"message": "Module 'signal' has no 'SIGBREAK' member",
	"source": "pylint",
	"startLineNumber": 471,
	"startColumn": 27,
	"endLineNumber": 471,
	"endColumn": 27
}

**Comment by luminoleon** [comment]
我认为这个不会影响正常使用。
如果真的不能用的话，可以删掉470、471行的内容

```python
if "SIGBREAK" in dir(signal):
    signal.signal(signal.SIGBREAK, self._quit)
```

**Comment by iso-lib** [comment]
> 我认为这个不会影响正常使用。 如果真的不能用的话，可以删掉470、471行的内容
> 
> ```python
> if "SIGBREAK" in dir(signal):
>     signal.signal(signal.SIGBREAK, self._quit)
> ```

谢谢,,已确认该错误不影响使用.
