### ISSUE TITLE
第一次运行的时候因为网络原因中断了,第二次运行就报错了

### ISSUE THREAD

**Issue by lq-259** [luminoleon/epicgames-claimer#16]
root@localhost:~/epic# python3 main.py
[Sun Oct 10 19:45:56 2021] Claimer started.
Traceback (most recent call last):
  File "epicgames_claimer.py", line 630, in <module>
    main()
  File "epicgames_claimer.py", line 612, in main
    claimer = epicgames_claimer(args.data_dir, headless=not args.no_headless, chromium_path=args.chromium_path, notifications=claimer_notifications)
  File "epicgames_claimer.py", line 67, in __init__
    self.open_browser()
  File "epicgames_claimer.py", line 543, in open_browser
    return self._loop.run_until_complete(self._open_browser_async())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "epicgames_claimer.py", line 114, in _open_browser_async
    executablePath=self.chromium_path,
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 148, in launch
    self.cmd, **options, )
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome'

希望能看一下

**Comment by lq-259** [comment]
> 可以参考下这个，用自己安装的浏览器来运行
> 
> [疑难解答/运行Python脚本在小内存或ARM设备上](https://github.com/luminoleon/epicgames-claimer/blob/main/docs/troubleshooting.md#%E8%BF%90%E8%A1%8Cpython%E8%84%9A%E6%9C%AC%E5%9C%A8%E5%B0%8F%E5%86%85%E5%AD%98%E6%88%96arm%E8%AE%BE%E5%A4%87%E4%B8%8A)

可以了，现在这个警告会是什么原因
Warning: Node is either not visible or not an HTMLElement

**Comment by luminoleon** [comment]
> > > > 可以参考下这个，用自己安装的浏览器来运行
> > > > [疑难解答/运行Python脚本在小内存或ARM设备上](https://github.com/luminoleon/epicgames-claimer/blob/main/docs/troubleshooting.md#%E8%BF%90%E8%A1%8Cpython%E8%84%9A%E6%9C%AC%E5%9C%A8%E5%B0%8F%E5%86%85%E5%AD%98%E6%88%96arm%E8%AE%BE%E5%A4%87%E4%B8%8A)
> > > 
> > > 
> > > 可以了，现在这个警告会是什么原因 Warning: Node is either not visible or not an HTMLElement
> > 
> > 
> > 应该是某个节点没有被找到（不在当前页面显示的区域里或者不存在），似乎是某个元素没有被正确识别到。 如果不是重复出现的话，忽略掉就好。
> 
> 重复出现后登录失败了 ] Warning: Node is either not visible or not an HTMLElement [Sun Oct 10 21:53:16 2021] Warning: Node is either not visible or not an HTMLElement [Sun Oct 10 21:54:48 2021] Warning: Node is either not visible or not an HTMLElement [Sun Oct 10 21:55:57 2021] Warning: Node is either not visible or not an HTMLElement [Sun Oct 10 21:56:59 2021] Warning: Node is either not visible or not an HTMLElement [Sun Oct 10 21:56:59 2021] Error: Login failed.

我没办法确定出现这个问题的原因，我刚测试了下是正常的没有报错。
可以看一下目录里生成的screenshot.png确定一下具体是什么状况。

**Comment by lq-259** [comment]
> > > > > 可以参考下这个，用自己安装的浏览器来运行
> > > > > [疑难解答/运行Python脚本在小内存或ARM设备上](https://github.com/luminoleon/epicgames-claimer/blob/main/docs/troubleshooting.md#%E8%BF%90%E8%A1%8Cpython%E8%84%9A%E6%9C%AC%E5%9C%A8%E5%B0%8F%E5%86%85%E5%AD%98%E6%88%96arm%E8%AE%BE%E5%A4%87%E4%B8%8A)
> > > > 
> > > > 
> > > > 可以了，现在这个警告会是什么原因 Warning: Node is either not visible or not an HTMLElement
> > > 
> > > 
> > > 应该是某个节点没有被找到（不在当前页面显示的区域里或者不存在），似乎是某个元素没有被正确识别到。 如果不是重复出现的话，忽略掉就好。
> > 
> > 
> > 重复出现后登录失败了 ] Warning: Node is either not visible or not an HTMLElement [Sun Oct 10 21:53:16 2021] Warning: Node is either not visible or not an HTMLElement [Sun Oct 10 21:54:48 2021] Warning: Node is either not visible or not an HTMLElement [Sun Oct 10 21:55:57 2021] Warning: Node is either not visible or not an HTMLElement [Sun Oct 10 21:56:59 2021] Warning: Node is either not visible or not an HTMLElement [Sun Oct 10 21:56:59 2021] Error: Login failed.
> 
> 我没办法确定出现这个问题的原因，我刚测试了下是正常的没有报错。 可以看一下目录里生成的screenshot.png确定一下具体是什么状况。

![screenshot](https://user-images.githubusercontent.com/60541200/136701609-aa7cf3aa-4217-4d6f-a8b3-06f675d2ac51.png)
这是不是网络问题啊
