### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by kevinbakbak** [luminoleon/epicgames-claimer#19]
进行到这里
sudo sh install_dependencies.sh

报错如下
Note, selecting 'libgcc-s1' instead of 'libgcc1'
E: Unable to locate package libappindicator1

----------------
uname -a
Linux racknerd-c8bf9b 5.11.22-bbrplus #1 SMP Sun Aug 22 14:57:38 CST 2021 x86_64 GNU/Linux

python --version
Python 2.7.18

**Comment by kevinbakbak** [comment]
> 
> 
> 进行到这里
> sudo sh install_dependencies.sh
> 
> 报错如下
> Note, selecting 'libgcc-s1' instead of 'libgcc1'
> E: Unable to locate package libappindicator1
> 
> uname -a
> Linux racknerd-c8bf9b 5.11.22-bbrplus #1 SMP Sun Aug 22 14:57:38 CST 2021 x86_64 GNU/Linux
> 
> python --version
> Python 2.7.18

切换python3.9后报错一样

**Comment by luminoleon** [comment]
你试一下运行sudo apt update，然后再运行sudo sh install_dependencies.sh试一下。
或者在报错后运行sudo apt -f install。

**Comment by kevinbakbak** [comment]
@luminoleon 
运行成功！感谢

另外请问
python3 main.py -u 用户名 -p 密码 -r 09:00 -o -a --chromium-path /usr/bin/google-chrome

这样就可以每日自动运行了吗，运行了一次提示成功抓取并退出了

**Comment by luminoleon** [comment]
加了-o参数就只运行一次然后退出，去掉-o就可以每天自动运行了。
