### ISSUE TITLE
在云服务器上如何使用呢

### ISSUE THREAD

**Issue by Cruii** [luminoleon/epicgames-claimer#2]
无桌面环境的云服务器如何使用呢  userdata如何而来呢

**Comment by luminoleon** [comment]
如果是Linux系统的云服务器，可以先安装Docker，然后运行`docker run -it luminoleon/epicgames-claimer`。
如果没有已存在的User_Data会提示你输入邮箱和密码完成登录，之后登录信息会被保存在User_Data里。

我不建议你在Linux服务器里直接运行这个Python脚本。在Docker镜像里，浏览器依赖和桌面环境都是打包好的。

另外，使用docker命令的-v参数可以把User_Data保存到本地，这样以后构建新的容器就不需要重新登录了。

**Comment by Cruii** [comment]
好的 非常谢谢
