### ISSUE TITLE
我是否应该继续维护此项目

### ISSUE THREAD

**Issue by luminoleon** [luminoleon/epicgames-claimer#2]
这个已经被禁过一次了。
虽然我又上传了一个，但不保证将来不会被我自己或者GitHub官方删除。
或许我现在就应该删掉它，只维护Docker版本？
另外在其他网站看到了有Epic用户被封的说法，或许我应该全部删掉不再维护？

**Comment by llwijvbw123** [comment]
好歹也是自己写的代码 :)

**Comment by luminoleon** [comment]
> 好歹也是自己写的代码 :)

我担心这么搞把GitHub账号给整没了……我现在还不确定是不是Actions的问题

**Comment by gdracula** [comment]
Epic会因为使用这个封禁用户？

**Comment by luminoleon** [comment]
> Epic会因为使用这个封禁用户？

我是在别的网站看到的（<https://www.appinn.com/epicgames-claimer-docker/>），但是目前没有人和我反馈账号被封的问题。我自己有一堆测试用的账号，包括我自己使用的账号，都没有被封。

**Comment by insoxin** [comment]
> > Epic会因为使用这个封禁用户？
> 
> 我是在别的网站看到的（https://www.appinn.com/epicgames-claimer-docker/），但是目前没有人和我反馈账号被封的问题。我自己有一堆测试用的账号，包括我自己使用的账号，都没有被封。

被封是因为Actions,因为同款项目还有GitHub还有其他的,几千的star 稳定好久了

**Comment by gdracula** [comment]
> > > Epic会因为使用这个封禁用户？
> > 
> > 
> > 我是在其他网站上看到的（[https://www.appinn.com/epicgames-claimer-docker/），目前没有人和测试我的账号被封的问题。我自己有操作的账号，包括我自己使用的账号，都没有被封。]
> 
> 被封是因为行动，因为同款还有GitHub还有其他的，同项目的明星稳定好久了

用actions的话，封的是github账户吧？

**Comment by insoxin** [comment]
> > > > Epic会因为使用这个封禁用户？
> > > 
> > > 
> > > 我是在其他网站上看到的（[https://www.appinn.com/epicgames-claimer-docker/），目前没有人和测试我的账号被封的问题。我自己有操作的账号，包括我自己使用的账号，都没有被封。]
> > 
> > 
> > 被封是因为行动，因为同款还有GitHub还有其他的，同项目的明星稳定好久了
> 
> 用actions的话，封的是github账户吧？

看你号新旧活跃度,之前有个新号只用了action直接封号,我现在这个比较活跃,封了action功能.而且有github客服的,被封可以删库申请解封,工单时间大概三个月比较长
