### ISSUE TITLE
平台不兼容

### ISSUE THREAD

**Issue by monkey-sking** [luminoleon/epicgames-claimer#22]
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by luminoleon** [comment]
目前docker镜像只编译了AMD64版本，我试一下能不能弄成全平台的。

当然你也可以直接用Python脚本。

**Comment by Csania-AM** [comment]
arm64用户看到这个就放心了

**Comment by Csania-AM** [comment]
> 目前docker镜像只编译了AMD64版本，我试一下能不能弄成全平台的。
> 
> 当然你也可以直接用Python脚本。

arm64用户看到这个就放心了

**Comment by luminoleon** [comment]
Docker镜像有ARM版本了，但是我没有用来测试的ARM设备。我猜应该没什么bug吧……
