### ISSUE TITLE
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443)

### ISSUE THREAD

**Issue by 10467106** [luminoleon/epicgames-claimer#24]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url 
可否把 HOST 文件直接改掉呢？
199.232.68.133 raw.githubusercontent.com 
这个现在可用。

**Comment by luminoleon** [comment]
可以。Docker镜像需要用`--add-host 域名:IP地址`添加host，直接修改系统的hosts没有效果。
