### ISSUE TITLE
请问下长时间会自动退出吗，总不能一直运行吧

### ISSUE THREAD

**Issue by smmya** [luminoleon/epicgames-claimer#27]
请问一下如果用cron自动化运行可以在领取完游戏后的一段时间后自动退出进程吗

**Comment by luminoleon** [comment]
可以加--once参数或者设置环境变量ONCE=true，领取完游戏后就会退出。

**Comment by smmya** [comment]
> 可以加--once参数或者设置环境变量ONCE=true，领取完游戏后就会退出。

使用-o参数是只会领取一个就退出执行对吧，那如果在epic同时放出两款免费游戏时使用-o是只会领取第一款是吗

**Comment by luminoleon** [comment]
> > 可以加--once参数或者设置环境变量ONCE=true，领取完游戏后就会退出。
> 
> 使用-o参数是只会领取一个就退出执行对吧，那如果在epic同时放出两款免费游戏时使用-o是只会领取第一款是吗

是所有的周免，包括周免的所有免费DLC，都会被一次领取。不加-o参数是每天都会去尝试领取，加了-o就是这次领取完就直接退出了。

**Comment by smmya** [comment]
> > > 可以加--once参数或者设置环境变量ONCE=true，领取完游戏后就会退出。
> > 
> > 
> > 使用-o参数是只会领取一个就退出执行对吧，那如果在epic同时放出两款免费游戏时使用-o是只会领取第一款是吗
> 
> 是所有的周免，包括周免的所有免费DLC，都会被一次领取。不加-o参数是每天都会去尝试领取，加了-o就是这次领取完就直接退出了。

谢谢你的回答，你的项目非常方便和实用，已star，
