### ISSUE TITLE
:bug: 领取失败

### ISSUE THREAD

**Issue by Oreomeow** [luminoleon/epicgames-claimer#28]
## `screenshot.png` 如下
![image](https://user-images.githubusercontent.com/62660101/139590733-da6cf93d-fd10-4a57-aa2d-a3da1babadb6.png)

**Comment by Oreomeow** [comment]
```text
EpicGames Claimer: 错误！

领取失败。Check claim result failed: DARQ: Complete Edition.
```

**Comment by luminoleon** [comment]
在领取游戏的时候有可能会跳出人机验证，我觉得应该是这个问题。这个问题等人机验证不跳出了就没有了（可能过几个小时）。

我以后大概会在遇到这个问题的时候多加一个提示。

**Comment by Oreomeow** [comment]
OK，这个错误是我之前采用 alpine 容器内 py 运行产生的，换了 Ubuntu 基础镜像的 docker 就可以了，alpine 确实有点问题
