### ISSUE TITLE
请问 用云函数的时候 触发器要多久一次呢?

### ISSUE THREAD

**Issue by GB-png** [luminoleon/epicgames-claimer#29]

**Comment by luminoleon** [comment]
每周至少触发一次就可以了。为了避免领取失败，可以触发的稍微频繁一点，比如每天或者每两天执行一次，或者开启通知推送让自己知道领取的结果。

**Comment by GB-png** [comment]
感谢大佬回复,我转用docker跑了,添加了tg通知,dokcer跑的时候怎么可以看日志是否登陆成功呢?
能否建议增加一个消息推送的测试消息呢?第一次配置的时候可以确认自己是成功的,再次感谢🙏

**Comment by luminoleon** [comment]
> 感谢大佬回复,我转用docker跑了,添加了tg通知,dokcer跑的时候怎么可以看日志是否登陆成功呢? 能否建议增加一个消息推送的测试消息呢?第一次配置的时候可以确认自己是成功的,再次感谢🙏

可以用`docker logs 容器名称或ID` 查看docker日志。

我可以在下一个版本里加上一条测试的通知推送。

**Comment by GB-png** [comment]
大佬🐮
