### ISSUE TITLE
欧洲区的epic账号在购买界面的额外确认操作

### ISSUE THREAD

**Issue by vsxd** [luminoleon/epicgames-claimer#3]
EU区域的账号应该是因为法律原因，会多出一步确认操作。所以脚本会卡在如下图的界面中：

![screenshot.png](https://i.loli.net/2021/09/17/zebmrv8M3qD9xc4.png)

解决方法其实很简单，在`epicgames_claimer.py`的309行下方非常粗暴地加入
`await self._click_async("#purchaseAppContainer > div.payment-overlay > div.payment-overlay__wrap > div > div > div.payment-confirm__actions > button.payment-btn.payment-confirm__btn.payment-btn--primary", timeout=60000)`即可。亲测已经能够正常领取，但这会影响其它区域的账户，所以没有提pr。

感觉对于非EU的账户，判断有没有这个按钮，然后再确定是否点击即可？

**Comment by luminoleon** [comment]
等我新注册个账号试一下就加

**Comment by luminoleon** [comment]
最新版1.5.1应该已经可以了。

**Comment by vsxd** [comment]
感谢，应该没问题了
