### ISSUE TITLE
docker领取漏游戏

### ISSUE THREAD

**Issue by marigold233** [luminoleon/epicgames-claimer#37]
![image](https://user-images.githubusercontent.com/62014410/142595762-98328e71-37a4-4f17-bfbf-d2812be2da90.png)

本周有三个游戏，第二个没领取。再启动个容器测试还是没有把第二个领取。

**Comment by luminoleon** [comment]
目前判断是否是周免游戏的逻辑是这样的：
    接口获取折扣游戏的信息：<https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions>
    如果从接口返回游戏的原价（originalPrice）不是0，而且折扣价格（discountPrice）是0，就认为这个游戏是一个周免游戏。
但是这个游戏原价返回的结果是0，就很奇怪。

我看看能不能换一种判断的逻辑。

**Comment by luminoleon** [comment]
v1.6.4我改了判断条件，应该是没问题了
