### ISSUE TITLE
运行提示超时

### ISSUE THREAD

**Issue by fatinghenji** [luminoleon/epicgames-claimer#4]
![image](https://user-images.githubusercontent.com/37131177/120024980-8fdd5400-c022-11eb-99e5-dd068d24ed27.png)
这个问题我在pc和服务器端都碰到了。
我没有设置二步验证

**Comment by luminoleon** [comment]
我注册了一个新的Epic账号并且尝试运行这个脚本，没有出现这个问题。

可能Epic商城在弹出订单页面之前，弹出了其他的对话框。或者你所使用的IP地址领取了太多免费游戏而被Epic限制领取。

你可以在你的电脑上，在epicgames_claimer.exe所在的目录下运行`.\epicgames_claimer.exe --headful`在浏览器中查看在弹出订单页面之前，是否出现了其他的提示，阻止了订单的创建。

**Comment by fatinghenji** [comment]
问题找到了，没有认证邮箱导致的报错……
