### ISSUE TITLE
1.6.4版本腾讯云函数一直报错

### ISSUE THREAD

**Issue by wzgrx** [luminoleon/epicgames-claimer#40]
START RequestId:a9539c3e-9620-441b-95ef-267c15654594

Using selector: EpollSelector

ERROR RequestId:a9539c3e-9620-441b-95ef-267c15654594 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/epicgames_claimer.py\", line 944, in main_handler\n    claimed_item_titles = main(args, raise_error=True)\n  File \"/var/user/epicgames_claimer.py\", line 922, in main\n    claimer = EpicgamesClaimer(args.data_dir, headless=not args.no_headless, chromium_path=args.chromium_path, claimer_notifications=claimer_notifications, timeout=args.debug_timeout, debug=args.debug)\n  File \"/var/user/epicgames_claimer.py\", line 287, in __init__\n    self.open_browser()\n  File \"/var/user/epicgames_claimer.py\", line 821, in open_browser\n    return self._loop.run_until_complete(self._open_browser_async())\n  File \"/var/lang/python3/lib/python3.6/asyncio/base_events.py\", line 466, in run_until_complete\n    return future.result()\n  File \"/var/user/epicgames_claimer.py\", line 337, in _open_browser_async\n    executablePath=self.chromium_path,\n  File \"/var/user/pyppeteer/launcher.py\", line 307, in launch\n    return await Launcher(options, **kwargs).launch()\n  File \"/var/user/pyppeteer/launcher.py\", line 149, in launch\n    self.cmd, **options, )\n  File \"/var/lang/python3/lib/python3.6/subprocess.py\", line 707, in __init__\n    restore_signals, start_new_session)\n  File \"/var/lang/python3/lib/python3.6/subprocess.py\", line 1326, in _execute_child\n    raise child_exception_type(errno_num, err_msg)\nFileNotFoundError: [Errno 2] No such file or directory: '/var/user/chrome-linux/chrome'","statusCode":430}

END RequestId:a9539c3e-9620-441b-95ef-267c15654594

Report RequestId:a9539c3e-9620-441b-95ef-267c15654594 Duration:15ms Memory:128MB MemUsage:25.914062MB

**Comment by luminoleon** [comment]
你看一下src目录里有没有chrome-linux这个文件夹，或许chrome没有被正确安装

**Comment by wzgrx** [comment]
> 你看一下src目录里有没有chrome-linux这个文件夹，或许chrome没有被正确安装

解决了，谢谢大佬
