### ISSUE TITLE
好哥哥，出错了。Waiting for selector "#purchase-app button[class*=confirm]:not([disabled])" failed: timeout 180000ms exceeds.

### ISSUE THREAD

**Issue by shaul-xu** [luminoleon/epicgames-claimer#43]
![image](https://user-images.githubusercontent.com/39487412/143519324-a85fcda6-5f31-49e5-b561-58817b55db47.png)

**Comment by shaul-xu** [comment]
系统是 `ubuntu18`。
神奇的事情是，我用 macos 运行该 image 不会出错可以正常 run 起来。都是刚 pull 的最新的 image

**Comment by luminoleon** [comment]
我猜大概是我刚更新了一个版本，所以你macos上运行的是不一样的版本。你更新下镜像试一试

**Comment by shaul-xu** [comment]
> 

哇，mac 刚重新又 pull 了一下，mac 上还是 ok 的

**Comment by shaul-xu** [comment]
> > 
> 
> 哇，mac 刚重新又 pull 了一下，mac 上还是 ok 的

我在 `Ubuntu18.x` 上重新 pull 了一次，返现还是不行，我也不知道了，搞不懂。。。

**Comment by luminoleon** [comment]
要不你试一下运行这个`docker run -it --rm luminoleon/epicgames-claimer -v`看看版本号是不是1.6.5

**Comment by shaul-xu** [comment]
> 

我重启了一下机器，正常了。多谢大佬

**Comment by marigold233** [comment]
> 要不你试一下运行这个`docker run -it --rm luminoleon/epicgames-claimer -v`看看版本号是不是1.6.5

我也有这个问题，也是ubuntu18.04，程序 版本号是：1.6.4。我是规定每天上午十点运行的。
![image](https://user-images.githubusercontent.com/62014410/143839419-5cb900c8-2878-4384-a585-b777a41fceed.png)
