### ISSUE TITLE
pyppeteer.errors.BrowserError: Browser closed unexpectedly

### ISSUE THREAD

**Issue by cyb233** [luminoleon/epicgames-claimer#44]
![image](https://user-images.githubusercontent.com/39186981/143531252-9b86e6a0-99e2-465c-b471-63ba378b2c5a.png)

运行平台：

![20211126112932](https://user-images.githubusercontent.com/39186981/143531378-fbe89b3f-2c27-4682-8ec6-297e0410cbf1.png)

运行方式：
```bat
@echo off&TITLE EpicGame
set http_proxy=http://localhost:50401
set https_proxy=http://localhost:50401
pip install --upgrade pip
pip install -r requirements.txt
python main.py -u email -p password -a
pause
```

**Comment by luminoleon** [comment]
或许可以试一下用自己下载的Chromium替代自动下载的版本 <https://download-chromium.appspot.com>
`--chromium-path chome.exe的路径`

**Comment by cyb233** [comment]
`-c "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"`
出现
`epicgames_claimer.py: error: unrecognized arguments: Files (x86)\Google\Chrome\Application\chrome.exe`

**Comment by luminoleon** [comment]
> `-c "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"` 出现 `epicgames_claimer.py: error: unrecognized arguments: Files (x86)\Google\Chrome\Application\chrome.exe` 为啥加了引号还会被截断？

这个应该是main.py处理参数的时候出的bug（我才注意到）。
先这样：把application文件夹直接复制到main.py所在的目录，然后路径用`Application/chrome.exe`
我之后会把这个bug修好。

**Comment by cyb233** [comment]
![image](https://user-images.githubusercontent.com/39186981/143574878-6836b0d2-58ee-4c80-ac4e-73abe96a55aa.png)
再次出现此问题
chrome版本96.0.4664.45（正式版本） （32 位）

等我再下个Chromium看看

**Comment by luminoleon** [comment]
> ![image](https://user-images.githubusercontent.com/39186981/143574878-6836b0d2-58ee-4c80-ac4e-73abe96a55aa.png) 再次出现此问题 chrome版本96.0.4664.45（正式版本） （32 位）
> 
> 等我再下个Chromium看看

或许可以试一试直接打开浏览器，看能不能正常打开，以及报了什么错没有，可能会有所帮助

**Comment by cyb233** [comment]
Chromium启动状态下仍有此问题
![image](https://user-images.githubusercontent.com/39186981/143576369-6eb9c14c-7556-461c-a298-565146b5591c.png)

**Comment by luminoleon** [comment]
我想我可能发现原因了，我创建了个bat运行那段指令，出现了相同的问题。浏览器被正确打开了，但是脚本似乎没有意识到浏览器已经被打开了。

顺便检查一下后台进程，可能开了一堆浏览器进程，需要手动结束它们。

**Comment by luminoleon** [comment]
去掉这两句就正常了。
```cmd
set http_proxy=http://localhost:10809
set https_proxy=http://localhost:10809
```
但是我并不知道原因。可能是pyppeteer或者puppeteer的bug。

我还注意到了高版本浏览器的User_Data不能用于低版本，需要手动删除掉它。

**Comment by cyb233** [comment]
反复试了几遍，确实是该语句导致的，原本只是顺便试试，没想到诱发了这个问题，完全没联想到这一点上

不过也顺便发现了些其他bug还不错

顺便，真的给我启动了好多chrome啊😂

我觉得这个经历可以总结进已知问题了

**Comment by cyb233** [comment]
嗯，还是先开着以防忽略：
参数空格截断【bug】

**Comment by longbowapache** [comment]
添加
no_proxy=localhost,127.0.0.1
NO_PROXY=localhost,127.0.0.1
即可
