### ISSUE TITLE
运行时显示更新出错这个有什么影响吗 ？

### ISSUE THREAD

**Issue by wyap-echo** [luminoleon/epicgames-claimer#5]
[Fri Sep 17 20:22:17 2021] Warning: Check for update failed. 'ascii' codec can't decode byte 0xef in position 1984: ordinal not in range(128)

**Comment by luminoleon** [comment]
不影响。不加--auto-update参数就不会出这个warning了。

自动更新目前不能用，因为这个repo被封过一次。我想弄一个更好的更新方式，不通过GitHub。
在这之前自动更新会一直不可用。

**Comment by wyap-echo** [comment]
> 不影响。不加--auto-update参数就不会出这个warning了。
> 
> 自动更新目前不能用，因为这个repo被封过一次。我想弄一个更好的更新方式，不通过GitHub。
> 在这之前自动更新会一直不可用。

谢谢
