### ISSUE TITLE
docker带参数创建容器失败

### ISSUE THREAD

**Issue by github-h** [luminoleon/epicgames-claimer#50]
![图片](https://user-images.githubusercontent.com/49114731/144640716-9f54be85-821a-4627-b225-ea8fa25a71fa.png)

我想在创建容器的时候带上 
`-n epic -r 10:00 -a -pwx “微信” -u 邮箱 -p 密码 -t 两步认证`

但是每次运行后就回弹一个1.6.6的版本号，`docker ps -a`查看容器并没有运行

我尝试先`docker run -it luminoleon/epicgames-claimer`有本地登录数据再`-v ~/epicgames_claimer/User_Data:/User_Data`也不行

我是哪里搞错了么？

**Comment by luminoleon** [comment]
-v要加在镜像前面，加到后面参数就传递给脚本了。这个是Docker的参数

**Comment by github-h** [comment]
若之前保存了账号信息到本地目录 开启定时、自动更新、微信推送

`docker run -v ~/epicgames_claimer/User_Data:/User_Data --name epic luminoleon/epicgames-claimer -r 10:00 -a -pwx "AAAAAAAA,BBBBBB,@all,CCCCC,DDDDDDD"`


若第一次登录并使用无交互  开启定时、自动更新、微信推送

`docker run --name epic luminoleon/epicgames-claimer -r 10:00 -a -pwx "AAAAAAAA,BBBBBB,@all,CCCCC,DDDDDDD" -u username -p password -t totp`

**Comment by github-h** [comment]
是参数前后的问题  感谢回答
