### ISSUE TITLE
请教一下 pyppeteer 相关问题

### ISSUE THREAD

**Issue by Oreomeow** [luminoleon/epicgames-claimer#52]
![image](https://user-images.githubusercontent.com/62660101/144731259-dd87a3e4-fca1-4e92-9aa7-094b1563be28.png)

`python epicgames_claimer.py -u xxx -p xxx -n`

然后一直卡在这里，但是用 selenium 测试简单脚本是正常的，百度之类的能打开

**Comment by luminoleon** [comment]
有些版本的浏览器貌似不能控制，会卡住。自动下载的浏览器或许没问题。而且有一点，我加了--disable-infobars，--blink-settings=imagesEnabled=false这两个浏览器参数，应该没有上面的横幅还有一个不显示图片的图标。

**Comment by Oreomeow** [comment]
@luminoleon 这就尴尬了，是自动下载的

```python
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch(devtools=True)
    page = await browser.newPage()
    await page.goto('https://www.baidu.com')
    await asyncio.sleep(100)

asyncio.get_event_loop().run_until_complete(main())
```
这个都不行

**Comment by Oreomeow** [comment]
![image](https://user-images.githubusercontent.com/62660101/144731685-5c37af23-7710-4372-a5f8-87fe48212635.png)

发错了 epic 是这个

**Comment by luminoleon** [comment]
我觉得可能和这个问题比较像 #44
环境变量里有https_proxy，http_proxy这两个貌似脚本就只打开浏览器，然后就不管了，退出脚本浏览器还会留在后台。

**Comment by Oreomeow** [comment]
![image](https://user-images.githubusercontent.com/62660101/144732319-bf8d0781-ee90-4677-81a5-1a213a22cc84.png)

```python
import time

from selenium import webdriver

browser = webdriver.Chrome()
browser.get("http://www.baidu.com")
browser.find_element_by_id("kw").send_keys("selenium")
browser.find_element_by_id("su").click()
time.sleep(5)
browser.quit()
```

我试试看把 pyppeteer 自动安装的卸载自己安装试试，selenium 毫无问题

**Comment by Oreomeow** [comment]
https://github.com/pyppeteer/pyppeteer/issues/276

**Comment by Oreomeow** [comment]
https://github.com/pyppeteer/pyppeteer/issues/305

解决了太意外了

因为我的 python 版本是 3.10.0，pip install websockets -U 就好了
