### ISSUE TITLE
腾讯云函数的变量在哪里设置啊，找了半天没找到

### ISSUE THREAD

**Issue by 666lbwnb** [luminoleon/epicgames-claimer#54]
如题

**Comment by luminoleon** [comment]
函数管理 函数配置 环境配置里添加环境变量

**Comment by 666lbwnb** [comment]
谢谢大佬，已成功运行，设置好了推送参数但是没有推送tg是咋回事

**Comment by Oreomeow** [comment]
@luminoleon 其实是判断写反了hhh

**Comment by Oreomeow** [comment]
```python
result_message = f"{NOTIFICATION_CONTENT_CLAIM_SUCCEED}{claimed_item_titles}" if len(claimed_item_titles) else NOTIFICATION_CONTENT_OWNED_ALL
```

**Comment by 666lbwnb** [comment]
噢

**Comment by luminoleon** [comment]
> > https://github.com/luminoleon/epicgames-claimer/blob/c301298a3d54984ff5d4c2c1ad042e553e1a8ba3/epicgames_claimer.py#L1049
> > 
> > 应为：
> > ```python
> > result_message  =  f" { NOTIFICATION_CONTENT_CLAIM_SUCCEED } { claim_item_titles } "  if  len ( claim_item_titles ) else  NOTIFICATION_CONTENT_OWNED_ALL
> > ```
> 
> 改了然后没推送成功是咋回事

应该是国内的网连不上tg的原因吧，还有就是如果所有游戏都领了是没有推送的，只有领了游戏才有

**Comment by 666lbwnb** [comment]
> 

我云函数部署在硅谷，连的上tg。那这样还是得加一个判断的呀，如果都领了也推送一下

**Comment by 666lbwnb** [comment]
> > > https://github.com/luminoleon/epicgames-claimer/blob/c301298a3d54984ff5d4c2c1ad042e553e1a8ba3/epicgames_claimer.py#L1049
> > > 
> > > 应为：
> > > ```python
> > > result_message  =  f" { NOTIFICATION_CONTENT_CLAIM_SUCCEED } { claim_item_titles } "  if  len ( claim_item_titles ) else  NOTIFICATION_CONTENT_OWNED_ALL
> > > ```
> > 
> > 
> > 改了然后没推送成功是咋回事
> 
> 应该是国内的网连不上tg的原因吧，还有就是如果所有游戏都领了是没有推送的，只有领了游戏才有

我云函数部署在硅谷，连的上tg。那这样还是得加一个判断的呀，如果都领了也推送一下

**Comment by luminoleon** [comment]
> > > > https://github.com/luminoleon/epicgames-claimer/blob/c301298a3d54984ff5d4c2c1ad042e553e1a8ba3/epicgames_claimer.py#L1049
> > > > 
> > > > 应为：
> > > > ```python
> > > > result_message  =  f" { NOTIFICATION_CONTENT_CLAIM_SUCCEED } { claim_item_titles } "  if  len ( claim_item_titles ) else  NOTIFICATION_CONTENT_OWNED_ALL
> > > > ```
> > > 
> > > 
> > > 改了然后没推送成功是咋回事
> > 
> > 
> > 应该是国内的网连不上tg的原因吧，还有就是如果所有游戏都领了是没有推送的，只有领了游戏才有
> 
> 我云函数部署在硅谷，连的上tg。那这样还是得加一个判断的呀，如果都领了也推送一下

过段时间有空了就加

**Comment by luminoleon** [comment]
> https://github.com/luminoleon/epicgames-claimer/blob/c301298a3d54984ff5d4c2c1ad042e553e1a8ba3/epicgames_claimer.py#L1049
> 
> 应为：
> 
> ```python
> result_message = f"{NOTIFICATION_CONTENT_CLAIM_SUCCEED}{claimed_item_titles}" if len(claimed_item_titles) else NOTIFICATION_CONTENT_OWNED_ALL
> ```

好吧我才发现……

**Comment by luminoleon** [comment]
> > > > https://github.com/luminoleon/epicgames-claimer/blob/c301298a3d54984ff5d4c2c1ad042e553e1a8ba3/epicgames_claimer.py#L1049
> > > > 
> > > > 应为：
> > > > ```python
> > > > result_message  =  f" { NOTIFICATION_CONTENT_CLAIM_SUCCEED } { claim_item_titles } "  if  len ( claim_item_titles ) else  NOTIFICATION_CONTENT_OWNED_ALL
> > > > ```
> > > 
> > > 
> > > 改了然后没推送成功是咋回事
> > 
> > 
> > 应该是国内的网连不上tg的原因吧，还有就是如果所有游戏都领了是没有推送的，只有领了游戏才有
> 
> 我云函数部署在硅谷，连的上tg。那这样还是得加一个判断的呀，如果都领了也推送一下

加了，设置环境变量PUSH_WHEN_OWNED_ALL=true就可以了

**Comment by 666lbwnb** [comment]
> > > > > https://github.com/luminoleon/epicgames-claimer/blob/c301298a3d54984ff5d4c2c1ad042e553e1a8ba3/epicgames_claimer.py#L1049
> > > > > 
> > > > > 应为：
> > > > > ```python
> > > > > result_message  =  f" { NOTIFICATION_CONTENT_CLAIM_SUCCEED } { claim_item_titles } "  if  len ( claim_item_titles ) else  NOTIFICATION_CONTENT_OWNED_ALL
> > > > > ```
> > > > 
> > > > 
> > > > 改了然后没推送成功是咋回事
> > > 
> > > 
> > > 应该是国内的网连不上tg的原因吧，还有就是如果所有游戏都领了是没有推送的，只有领了游戏才有
> > 
> > 
> > 我云函数部署在硅谷，连的上tg。那这样还是得加一个判断的呀，如果都领了也推送一下
> 
> 加了，设置环境变量PUSH_WHEN_OWNED_ALL=true就可以了

谢谢大佬，后续能不能增加多账户的功能
