### ISSUE TITLE
请教一个参数的问题

### ISSUE THREAD

**Issue by ThingsWhy** [luminoleon/epicgames-claimer#58]
1.参数里面有两个参数-h与-n但是在底下并没有说明，想问一下作用
2.docker run里面需要加入-it吗，有什么影响吗
感谢

**Comment by luminoleon** [comment]
-h是显示说明文档，-n是关闭无头模式（显示浏览器窗口）

-it是让docker容器终端可以交互输入

**Comment by ThingsWhy** [comment]
多问一句，上述的三个参数在创建容器的时候是必要的吗

**Comment by luminoleon** [comment]
-h和-n不要加
-it是不带邮箱、密码参数的时候，需要交互输入才需要加

最简单的使用方法就是什么参数都不加（docker要加-it）

**Comment by ThingsWhy** [comment]
好的，谢谢大佬
