### ISSUE TITLE
Python版本可选参数--push-when-owned-all 有问题！

### ISSUE THREAD

**Issue by otherbanana** [luminoleon/epicgames-claimer#59]
使用参数 --push-when-owned-all 显示报错，如图所示：
![Snipaste_2021-12-13_21-26-53](https://user-images.githubusercontent.com/34509569/145821042-90b47422-c8f2-4c16-b469-547616856db4.png)

然后尝试使用 -push-when-owned-all 无报错

**Comment by luminoleon** [comment]
这个看起来不像是最新的版本，有--push-when-owned-all这个参数的版本还没有release。
-push-when-owned-all实际上相当于是加了`-p ush-when-owned-all`这个参数了，所以不会报错。

**Comment by otherbanana** [comment]
确实是的，版本不是最新的，更新就好了，谢谢
