### ISSUE TITLE
[Feature request]适配圣诞特惠（日签）

### ISSUE THREAD

**Issue by sino1641** [luminoleon/epicgames-claimer#60]
17日开始日签圣诞特惠，无法直接本脚本自动领取，提示：
```
[2021-12-17 01:39:02  WARN] We could not confirm your purchase at this time.  Please try again later.
[2021-12-17 01:42:05  WARN] Waiting for selector "#purchase-app button[class*=confirm]:not([disabled])" failed: timeout 180000ms exceeds.
[2021-12-17 01:42:17 ERROR] Failed to claim one item: We could not confirm your purchase at this time.  Please try again later.
```
而使用网页可以正常领取，领取流程也是照旧的。
这边没有电脑所以没法帮忙提供脚本下的有头浏览器截图。
望作者适配，感谢！

**Comment by marigold233** [comment]
+1

**Comment by luminoleon** [comment]
Epic换了新的订单链接，以前的似乎不能用了，我去适配一下

**Comment by Nickyromeo** [comment]
+1

**Comment by github-h** [comment]
> Epic换了新的订单链接，以前的似乎不能用了，我去适配一下

`docke run` 的时候加入了 `-a ` 参数，本次更新会自动同步么？还是需要额外操作比如 重新 pull and run

**Comment by luminoleon** [comment]
> > Epic换了新的订单链接，以前的似乎不能用了，我去适配一下
> 
> `docke run` 的时候加入了 `-a ` 参数，本次更新会自动同步么？还是需要额外操作比如 重新 pull and run

会自动同步，不需要再pull了

**Comment by fantasyxby** [comment]
+1

**Comment by YXHTom** [comment]
+1

**Comment by jsdfhasuh** [comment]
> > > Epic换了新的订单链接，以前的似乎不能用了，我去适配一下
> > 
> > 
> > `docke run` 的时候加入了 `-a ` 参数，本次更新会自动同步么？还是需要额外操作比如 重新 pull and run
> 
> 会自动同步，不需要再pull了

我想问问，怎么设置多个时间点运行任务

**Comment by luminoleon** [comment]
> > > > Epic换了新的订单链接，以前的似乎不能用了，我去适配一下
> > > 
> > > 
> > > `docke run` 的时候加入了 `-a ` 参数，本次更新会自动同步么？还是需要额外操作比如 重新 pull and run
> > 
> > 
> > 会自动同步，不需要再pull了
> 
> 我想问问，怎么设置多个时间点运行任务

目前不行，我以后弄个cron参数吧

**Comment by wsgfz** [comment]
辛苦啦~

**Comment by Nickyromeo** [comment]
谢谢大佬

**Comment by a251231** [comment]
> > > > > Epic换了新的订单链接，以前的似乎不能用了，我去适配一下
> > > > 
> > > > 
> > > > `docke run` 的时候加入了 `-a ` 参数，本次更新会自动同步么？还是需要额外操作比如 重新 pull and run
> > > 
> > > 
> > > 会自动同步，不需要再pull了
> > 
> > 我想问问，怎么设置多个时间点运行任务
> 
> 目前不行，我以后弄个cron参数吧

大佬 我重新拉的docker镜像 依然存在不能领取的情况 和这个issue相同

**Comment by sino1641** [comment]
> > > > > > Epic换了新的订单链接，以前的似乎不能用了，我去适配一下
> > > > > 
> > > > > 
> > > > > `docke run` 的时候加入了 `-a ` 参数，本次更新会自动同步么？还是需要额外操作比如 重新 pull and run
> > > > 
> > > > 
> > > > 会自动同步，不需要再pull了
> > > 
> > > 
> > > 我想问问，怎么设置多个时间点运行任务
> > 
> > 
> > 目前不行，我以后弄个cron参数吧
> 
> 大佬 我重新拉的docker镜像 依然存在不能领取的情况 和这个issue相同

你docker所在网络能不能直接访问github 内建的更新走`api.github.com`
（小白的话其实 用其他可以后台的方式或者直接腾讯云函数会更方便吧）
我这边18号的可以领取了

**Comment by shadow6336** [comment]
> > > > > > Epic换了新的订单链接，以前的似乎不能用了，我去适配一下
> > > > > 
> > > > > 
> > > > > `docke run` 的时候加入了 `-a ` 参数，本次更新会自动同步么？还是需要额外操作比如 重新 pull and run
> > > > 
> > > > 
> > > > 会自动同步，不需要再pull了
> > > 
> > > 
> > > 我想问问，怎么设置多个时间点运行任务
> > 
> > 
> > 目前不行，我以后弄个cron参数吧
> 
> 大佬 我重新拉的docker镜像 依然存在不能领取的情况 和这个issue相同

可试试拉dev的镜像，你可以去dockerhub里面看下tag，最近更新的是dev
docker-compose文件里的image: luminoleon/epicgames-claimer:dev

**Comment by github-h** [comment]
> > > Epic换了新的订单链接，以前的似乎不能用了，我去适配一下
> > 
> > 
> > `docke run` 的时候加入了 `-a ` 参数，本次更新会自动同步么？还是需要额外操作比如 重新 pull and run
> 
> 会自动同步，不需要再pull了

今天看并没有同步最新的更新，是哪里操作的不对么？怎么看起来是3天运行了一次啊
![图片](https://user-images.githubusercontent.com/49114731/146625756-8ed87c0a-05b2-47c1-aedc-0f668ed7a0e5.png)

创建docker用的是
`docker run -v ~/epicgames_claimer/User_Data:/User_Data --name epic luminoleon/epicgames-claimer-r 10:00 -a -pwx "@@@,@@,@@,@@"`

**Comment by luminoleon** [comment]
> > > > Epic换了新的订单链接，以前的似乎不能用了，我去适配一下
> > > 
> > > 
> > > `docke run` 的时候加入了 `-a ` 参数，本次更新会自动同步么？还是需要额外操作比如 重新 pull and run
> > 
> > 
> > 会自动同步，不需要再pull了
> 
> 今天看并没有同步最新的更新，是哪里操作的不对么？怎么看起来是3天运行了一次啊 ![图片](https://user-images.githubusercontent.com/49114731/146625756-8ed87c0a-05b2-47c1-aedc-0f668ed7a0e5.png)
> 
> 创建docker用的是 `docker run -v ~/epicgames_claimer/User_Data:/User_Data --name epic luminoleon/epicgames-claimer-r 10:00 -a -pwx "@@@,@@,@@,@@"`

现在应该可以更新了

**Comment by github-h** [comment]
> > > > > Epic换了新的订单链接，以前的似乎不能用了，我去适配一下
> > > > 
> > > > 
> > > > `docke run` 的时候加入了 `-a ` 参数，本次更新会自动同步么？还是需要额外操作比如 重新 pull and run
> > > 
> > > 
> > > 会自动同步，不需要再pull了
> > 
> > 
> > 今天看并没有同步最新的更新，是哪里操作的不对么？怎么看起来是3天运行了一次啊 ![图片](https://user-images.githubusercontent.com/49114731/146625756-8ed87c0a-05b2-47c1-aedc-0f668ed7a0e5.png)
> > 创建docker用的是 `docker run -v ~/epicgames_claimer/User_Data:/User_Data --name epic luminoleon/epicgames-claimer-r 10:00 -a -pwx "@@@,@@,@@,@@"`
> 
> 现在应该可以更新了

那我就是等明天他10点自动运行是吧
