### ISSUE TITLE
We could not confirm your purchase at this time.  Please try again later.

### ISSUE THREAD

**Issue by jiaoting** [luminoleon/epicgames-claimer#62]
We could not confirm your purchase at this time.  Please try again later.
![image](https://user-images.githubusercontent.com/12553424/146522718-40963c86-7945-46f6-8f62-c26df58da12d.png)

**Comment by e68862230** [comment]
遇到了同样的问题。。。

**Comment by VwEl** [comment]
一样

**Comment by Peter1224** [comment]
遇到了同样的问题。。。

**Comment by linlinago** [comment]
一样

**Comment by heyuhengmatt** [comment]
一样

**Comment by heyuhengmatt** [comment]
这个错误大概是由epic自己返回的

**Comment by fallenyy** [comment]
一样。。。手动能领取。。。。

**Comment by cpaig** [comment]
一样的错误

**Comment by Silentely** [comment]
一样

**Comment by suzengyi** [comment]
一样，用的docker，luminoleon/epicgames-claimer:latest-alpine，cookie登录

**Comment by luminoleon** [comment]
v1.6.11可以了，但是还不能自动领DLC。开了自动更新的会在下一次领取的时候更新脚本。Docker镜像之后我会上传。

**Comment by jiaoting** [comment]
> 

docker啥时候可以更新啊？已经4个小时了

**Comment by Silentely** [comment]
> > 
> 
> docker啥时候可以更新啊？已经4个小时了

已经更新了 自己切换到dev分支 参数加-a

**Comment by luminoleon** [comment]
> > > 
> > 
> > 
> > docker啥时候可以更新啊？已经4个小时了
> 
> 已经更新了 自己切换到dev分支 参数加-a

不需要dev，一般的镜像就可以

**Comment by gwentman** [comment]
使用了1.6.11的镜像，可以领取成功

**Comment by Yasin27878** [comment]
1.6.11可用，1.6.12仍然复现该问题 Failed to claim one item: We could not confirm your purchase at this time.  Please try again later.

**Comment by bbhxwl** [comment]
我也是，为什么呢。

**Comment by jiaoting** [comment]
更新新版就好了，另外docker使用dev分支，加上自动更新参数就好了



在 2021-12-20 15:03:00，"bbhxwl" ***@***.***> 写道：

我也是，为什么呢。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
