### ISSUE TITLE
有大佬说说docker拉取哪个镜像的吗？

### ISSUE THREAD

**Issue by 2375399351** [luminoleon/epicgames-claimer#63]
我是x86平台，![image](https://user-images.githubusercontent.com/34334506/146625062-9975dc27-8ecf-474e-8dbd-4aff090abc08.png)
现在拉取的latest，显示更新好了，但是还是无法领取，ping api.github.com是正常可以连接的

**Comment by shadow6336** [comment]
不是latest，是dev，你可以去dockerhub里面看下tag，最近更新的是dev
docker-compose文件里的image: luminoleon/epicgames-claimer:dev

**Comment by 2375399351** [comment]
> 不是latest，是dev，你可以去dockerhub里面看下tag，最近更新的是dev
> 
> docker-compose文件里的image: luminoleon/epicgames-claimer:dev

好的谢谢
