### ISSUE TITLE
能否考虑在启动时设定账户密码以及2FA验证码

### ISSUE THREAD

**Issue by Cruii** [luminoleon/epicgames-claimer#7]
epic好像可以支持备用的2FA验证码，能否实现在启动时就设定好账户信息。
就不用每次都交互输入了。

**Comment by luminoleon** [comment]
我会考虑。

**Comment by Cruii** [comment]
新功能不支持docker容器吗

**Comment by luminoleon** [comment]
目前docker版本可以添加参数`-v ~/epicgames-claimer/User_Data:/User_Data`把登录信息保存在本地目录里，登录成功一次以后添加这个参数就不需要再登录了。

以后我会尝试添加一些其他的登录方式。

**Comment by luminoleon** [comment]
提个醒，现在docker容器可以在启动时设定账户和密码了。

格式是这样的:
`docker run -d luminoleon/epicgames-claimer -u 邮箱 -p 密码`

整个运行过程是无交互输入的，不支持输入双重验证码。
备用码使用一次就会失效，我认为不应该被用在这里。
