### ISSUE TITLE
云函数安装模块的命令是否有误？

### ISSUE THREAD

**Issue by jkluio78** [luminoleon/epicgames-claimer#8]
执行`pyppeteer-install`时没有用

`[root@ws-nbxwpj-0 src]# pyppeteer-install`
`bash: pyppeteer-install: command not found`

**Comment by luminoleon** [comment]
确实是我犯了个错误。

正确的命令应该是`bin/pyppeteer-install`

**Comment by jkluio78** [comment]
还是有报错

`[root@ws-nbxwpj-0 src]# bin/pyppeteer-install`
`Traceback (most recent call last):`
`  File "bin/pyppeteer-install", line 5, in <module>`
`    from pyppeteer.command import install`
`ModuleNotFoundError: No module named 'pyppeteer'`

![image](https://user-images.githubusercontent.com/74967641/134802359-096da8c0-2f95-4588-991f-da19203ecbcb.png)

**Comment by luminoleon** [comment]
好吧，我可能又弄错了些东西……

正确的命令应该是
```bash
mv bin/pyppeteer-install .
pyppeteer-install
```

**Comment by jkluio78** [comment]
第一个mv命令执行成功了，第二个还是报错，也许在云函数上没法运行这个文件

```
[root@ws-nbxwpj-0 src]# mv bin/pyppeteer-install .
[root@ws-nbxwpj-0 src]# pyppeteer-install
bash: pyppeteer-install: command not found
```
![image](https://user-images.githubusercontent.com/74967641/134803707-f9629041-6dc3-44ba-accb-cd1d110e92c4.png)

**Comment by luminoleon** [comment]
这次肯定没问题了（大概）
```bash
mv bin/pyppeteer-install .
./pyppeteer-install
```

**Comment by jkluio78** [comment]
这次没问题了，输入命令之后部署然后测试，看了输出日志都正常，但是没有收到server酱的推送，是只有入库了新游戏才有推送吗

**Comment by luminoleon** [comment]
> 这次没问题了，输入命令之后部署然后测试，看了输出日志都正常，但是没有收到server酱的推送，是只有入库了新游戏才有推送吗

是的，只有出错和领取到游戏会推送通知。

**Comment by jkluio78** [comment]
ok，作者要不在readme再加个说明
输入完命令以后需要点击部署按钮，否则直接点击测试的话还是会报错

**Comment by luminoleon** [comment]
> ok，作者要不在readme再加个说明
> 输入完命令以后需要点击部署按钮，否则直接点击测试的话还是会报错

好的
