### ISSUE TITLE
看了下源码，发现没有对图片验证识别的处理

### ISSUE THREAD

**Issue by Sloaix** [luminoleon/epicgames-claimer#8]
这是怎么做到的？即使打开了二次验证，依然会弹出图片验证码。

但是源码里面并没有对图片验证码这块的处理，也就是说应该会登录失败。

我看过很多python写的epic game的领取bot，但是大部分是用账号密码先获取token，通过token实现登录的。

很好奇，希望能够解答。

**Comment by luminoleon** [comment]
我早期做了大量工作试图绕过Epic服务器的bot检测。经过很多次的尝试之后，我发现了三种必定触发CAPTCHA的情况：
1. 浏览器有可疑特征；
2. 操作频率过高；
3. 登录时直接访问登录页面（不是从主页导航过去的）。

后两种很好解决，关键是隐藏浏览器的可疑特征。
起初我在虚拟桌面环境上运行的一个几乎完全正常的浏览器来避免被检测出，但这样使用不是很方便。
后来我查阅了很多资料（其中比较重要的一个：<https://github.com/puppeteer/puppeteer/issues/665>），最后成功隐藏了会被Epic服务器检测出的所有特征。

我不敢保证100%不会触发CAPTCHA，但就我自己的使用情况来看，目前还没有出现其他状况。

避开上面三种情况就可以直接在浏览器里完成登录操作了，不会跳出验证页面。

还有，隐藏浏览器特征的是这个函数`_headless_stealth_async`。
