### ISSUE TITLE
Repeated sending messages when the game is now owned

### ISSUE THREAD

**Issue by EraserKing** [luminoleon/epicgames-claimer#86]
Latest docker edition, dev tag

Environments variables of the docker container
```
PUSH_WHEN_OWNED_ALL=true
ONCE=true
```

Use crond to start the docker container and expect it exits after the game is claimed
`30 9 * * * docker restart epicgames-claimer`

Then I found the container doesn't exit as expected, and it keeps sending messages forever (game is claimed) until I manually shutdown the container.

**Comment by luminoleon** [comment]
Perhaps you have used some settings to automatically restart the Docker container after it exits. Check your settings or set `ONCE=false`.

**Comment by EraserKing** [comment]
Yes, sorry for that. I checked container settings and updated restart policy to no, then it looks okay now. 

I would also suggest write this tip into the guide for once, thanks
