### ISSUE TITLE
Offer

### ISSUE THREAD

**Issue by Divarion-D** [luminoleon/epicgames-claimer#89]
Someone add support for multiple languages for notifications. Convenient when notifications come, but I don’t know Chinese

**Comment by Oreomeow** [comment]
You can use deepl to translate the Chinese at the top of the script, then replace it with English and finally replace the script.

**Comment by Divarion-D** [comment]
What's the point in updating the lines at the top of the script if after the update everything returns to the original language. It is necessary that the script already have several copies with translations that could be selected via a console parameter.

**Comment by Oreomeow** [comment]
@luminoleon
So consider his multilingual log offer?

**Comment by luminoleon** [comment]
> @luminoleon So consider his multilingual log offer? 所以考虑下他的多语言日志提议？

It's not hard. I think I can add an argument for switching languages.

**Comment by Divarion-D** [comment]
Added in a27c7c42b4885a123d10e51c4d102f5b5db8f285
