### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version

### ISSUE THREAD

**Issue by NBY** [luminoleon/epicgames-claimer#9]
debian 10执行发现requests对urllib3和chardet有版本要求：

root@debian10:~/epicgames-claimer# python3 main.py --auto-update
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[Sun Sep 26 10:10:23 2021] Claimer started.

解决：
pip3 install urllib3==1.21.1 chardet==3.0.2

**Comment by luminoleon** [comment]
好的，我会把这个内容加到疑难解答里
