### ISSUE TITLE
Can i Change the Notification Language

### ISSUE THREAD

**Issue by darkero27** [luminoleon/epicgames-claimer#92]
I can't read Chinese, can I change the text of the notification to English?
![IMG_20211223_232750](https://user-images.githubusercontent.com/66249402/147267867-863d520b-a26f-4e3e-a84a-96de01590f37.jpg)

**Comment by Oreomeow** [comment]
You can use deepl to translate the Chinese at the top of the script, then replace it with English and finally replace the script.
