### ISSUE TITLE
why i cant get any notification 

### ISSUE THREAD

**Issue by darkero27** [luminoleon/epicgames-claimer#93]
![image](https://user-images.githubusercontent.com/66249402/147274106-a8bc3a1f-9677-4021-99ab-2da56a1830f3.png)
why i don't get notification of game i have taken when i enable "--push-when-owned-all", i only get notification when registering telegram only
![Screenshot_2021-12-24-00-31-15-935_org telegram messenger](https://user-images.githubusercontent.com/66249402/147274277-750cc30d-ce4b-4171-a554-4384fbec75ee.jpg)

**Comment by Clancyli** [comment]
python main.py -ptt "your telegram token" -pti "your chat id in telegram api page" --push-when-owned-all true

**Comment by luminoleon** [comment]
It was normal when I tested it. Check if your arguments are correct.

**Comment by darkero27** [comment]
> It was normal when I tested it. Check if your arguments are correct.

it just for the first time, if do it manually, it's not give the notification
![image](https://user-images.githubusercontent.com/66249402/147365864-662f73a6-0338-4c9d-a1e2-0c6ec8a87725.png)
